# ===============================
# Spring Boot Application Config
# ===============================
spring.application.name=test-case-management
server.port=8080

# ===============================
# MongoDB Configuration
# ===============================
spring.data.mongodb.uri=mongodb+srv://rishavrajbhagat123:<db_password>@cluster0.b2fnr.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=testcaseDB

# ===============================
# Swagger API Documentation
# ===============================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# ===============================
# Logging Configuration
# ===============================
logging.level.root=INFO
logging.level.org.springframework.web=DEBUG
logging.level.com.example.TestCaseManagement=DEBUG

# ===============================
# Enable Validation Messages
# ===============================
spring.messages.basename=messages
